name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: pitch
    attributes:
      label: Pitch
      description: describe the feature you'd like to see.
    validations:
      required: true