# .github/workflows/reusable-steps.yml
name: Reusable Workflow for Node.js Projects

on:
    workflow_call:
        inputs:
            node-version:
                description: 'Version de Node.js à utiliser'
                required: false
                default: '20'
                type: string

jobs:
    approval:
        # Ajout de l'environnement "production" avec une règle d'approbation
        runs-on: ubuntu-latest

        environment:
          name: production
        permissions:
          id-token: write
          contents: read
    
        steps:
          - name: Approval step
            run: echo "Waiting for approval to proceed with npm test."
    run-tests:
        runs-on: ubuntu-latest
        needs: approval

        steps:
            # Étape 1: Vérifie le code source
          - name: Checkout code
            uses: actions/checkout@v4.2.1

            # Étape 2: Utilise le meilleur conteneur pour npm
          - name: Set up Node.js environment
            uses: actions/setup-node@v4.0.4
            with:
                node-version: ${{ inputs.node-version }}

            # Étape 3: Installe les dépendances npm à partir du package.json
          - name: Install dependencies
            run: npm install

            # Étape 4: Exécute la collection Bruno CLI située dans src/test/bruno
          - name: Run Bruno collection
            run: npm test